version: '3'
services:
  service1:
    build:
      context: ./users
    ports:
      - "3003:3003"
    networks:
      - mynetwork

  service2:
     context: ./pharmacy
     ports:
      - "3007:3007"
     networks:
      - mynetwork



  service3:
    context: ./medecin
    ports:
      - "3004:3004"
    networks:
      - mynetwork

  service4:
    context: ./articles
    ports:
      - "3006:3006"
    networks:
      - mynetwork


  service5:
    context: ./appointment
    ports:
      - "3006:3006"
    networks:
      - mynetwork

  service6:
    context: ./api_gateway
    ports:
      - "3009:3009"
    networks:
      - mynetwork


  services7:
    context: ./api_gateway
    ports:
      - "3008:3008"
    networks:
      - mynetwork

      



networks:
  mynetwork:
    # Configuration du réseau
