version: '3'
services:
  service1:
    build:
      context: ./users
    ports:
      - "3000:3000"
    networks:
      - mynetwork

  service2:
     context: ./pharmacy
     ports:
      - "3001:3001"
     networks:
      - mynetwork



  service3:
    context: ./medecin
    ports:
      - "3002:3002"
    networks:
      - mynetwork

  service4:
    context: ./articles
    ports:
      - "3003:3003"
    networks:
      - mynetwork


  service5:
    context: ./appointments
    ports:
      - "3004:3004"
    networks:
      - mynetwork

  service6:
    context: ./api_gateway
    ports:
      - "3005:3005"
    networks:
      - mynetwork



networks:
  mynetwork:
    # Configuration du réseau
